#!/usr/bin/env python
# - coding: utf-8 -
# Copyright © 2012 Edward Smith
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

import os, sys

SUPPORTED_SUFFIX = ".webm"

if __name__ == "__main__":
    filenames = [fn for fn in os.listdir(os.curdir) 
                 if fn.endswith(SUPPORTED_SUFFIX)]
    for fn in filenames:
        newname = fn.replace("webm", "ogg")
        os.system("avconv -i \'%s\' -vn -acodec copy \'%s\'" % (fn, newname))
        
    ofnames = ['\'' + fn.replace("webm", "ogg") + '\'' for fn in filenames]
    for of in ofnames:
        os.system("vorbiscomment -w --tag \'album=YouTube' %s" % of)
    os.system("exfalso %s" % ofnames)
        
