#!/bin/bash

start_time="${3}"
duration="${4}"

palette="/tmp/palette.png"

filters="fps=15"

{ ffmpeg -v warning \
       -ss $start_time \
       -t $duration \
       -i "${1}" \
       -vf "$filters,palettegen" \
       -y $palette && 
  ffmpeg -v warning \
	 -ss $start_time \
	 -t $duration \
	 -i "${1}" \
	 -i $palette \
	 \ #-vf crop="${5}" # w:h:x:y, w by h pixels at (x,y) from top left
	 -lavfi "$filters [x]; [x][1:v] paletteuse" \
	 -y "${2}" 
} || exit 1;
# TODO: something with crops made with mplayer -vf rectangle -input conf=crop
# 
