#!/usr/bin/python
command = "gtcli list workdue"

import os

pipe = os.popen(command)

tasks = {}
for line in pipe.readlines():
    if ":" in line:
        continue
    else:
        chunks = filter(lambda s: s != '', line.split(" "))
        out = " ".join(chunks[1:])
        if not out.isspace():
            tasks[chunks[0]] = out.strip()
for (k,v) in tasks.iteritems():
    print v

    
