#!/bin/bash

if [ "$#" == "0" ]; then
    echo "Usage: $0 [hostname] <package1>...<packageN>"
    exit 1
fi

hostname=$1
shift

cmd="sudo vmbuilder kvm ubuntu --dest /var/lib/libvirt/images/$1 \
 --debug -v -o \
 --hostname $hostname \
 --mem 4096 --cpus 2 \
 --rootsize 20480 \
 --arch i386 \
 --flavour virtual \
 --components main,universe,multiverse,restricted \
 --libvirt qemu:///system \
 --suite precise \
 --ssh-user-key ~/.ssh/id_rsa.pub --ssh-key ~/.ssh/id_rsa.pub \
 --user $USER \
 --addpkg openssh-server --addpkg avahi-daemon --addpkg etckeeper \
 --addpkg byobu --addpkg nano --addpkg atool"

# start popping off arguments
addpkg=""
while (( "$#" )); do
    addpkg="${addpkg} --addpkg ${1}"
    shift
done

bash -c "${cmd} ${addpkg}"
virsh -c qemu:///system autostart $hostname

