#!/usr/bin/env python

import os
import random
import subprocess
import sys



if __name__ == "__main__":
    home = os.environ['HOME']
    project = random.choice(os.path.listdir("{}/Projects/".format(home)))
    subprocess.call("dowork {}".format(project))