#!/usr/bin/env python

import sys

sys.path.append("/home/tedks/Projects/randomline/")

from randomline import *

projects_file = "/home/tedks/Documents/personal/projects.txt"

if __name__ == "__main__":
    project = get_random_line(projects_file)[2:]
    print "Work on %s" % project
    
    

