#!/usr/bin/env python

import sys, array

# get the target file lines
target_fname = sys.argv[1]
lines = open(target_fname, "r").readlines()

# get the random number
index = array.array('L')
rand_source = open("/dev/random", "r")
index.fromfile(rand_source, 1)

# output
offset = (index[0] % len(lines))
print lines[offset]
