#!/usr/bin/env python

import sys, array

def get_random_line(target_fname):
    # get the target file lines
    linef = open(target_fname, "r")
    lines = linef.readlines()
    linef.close()
    
    # get the random number
    index = array.array('L')
    rand_source = open("/dev/random", "r")
    index.fromfile(rand_source, 1)
    
    # output
    offset = (index[0] % len(lines))
    return lines[offset].strip()

if __name__ == "__main__":
    print get_random_line(sys.argv[1])
    
