#!/usr/bin/python

import sys
from os import path, system, listdir
from pipes import quote
from time import sleep
from deluge_add import DelugeAdder

BASE_DEST = "/usr/share/warez/Downloads/what.cd"

def add_torrent(tpath, destpath, rename_on_success=False):
    da = DelugeAdder(BASE_DEST)
    if not da.add_torrent(tpath, path=destpath):
        print "Couldn't add torrent {}".format(tpath)
        return
    if rename_on_success:
        system("mv \"%s\" \"%s\"" % (quote(tpath), quote(tpath)+".added"))
    
def whatcd_add_path(artist_rip_dir, dest=None):
    if not dest:
        dest = path.join(BASE_DEST, 
                         path.split(path.basename(artist_rip_dir))[-1])
    for child in listdir(artist_rip_dir):
        if path.isdir(path.join(artist_rip_dir, child)):
            whatcd_add_path(path.join(artist_rip_dir, child),
                            path.join(dest, child))
        elif path.splitext(child)[1] == '.torrent':
            add_torrent(path.join(artist_rip_dir, child), dest)
        else:
            continue

if __name__ == '__main__':
    for d in sys.argv[1:]:
        whatcd_add_path(d)
    
